version: '3.8'
services:
  user-service:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/user-service
      - JWT_SECRET=your_jwt_secret
  mongo:
    image: mongo
    ports:
      - "27017:27017"
